# HOWTO: https://pre-commit.com/#usage
# pip3 install pre-commit
# pre-commit install -t pre-commit -t pre-push

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        exclude: archetypes|docs|data|layouts|resources|source-git|static|themes/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: https://github.com/packit/pre-commit-hooks
    rev: 3bf9afc5ede12a4ee26e9451f306edf255749396
    hooks:
      - id: check-rebase
        args:
          - https://github.com/packit/packit.dev.git
        stages: [manual, push]
